name: Development CI

on:
  push:
    branches: [master]
    paths-ignore: ['*.md']

jobs:

  Sast-Development:
    environment: development
    runs-on: ubuntu-latest
    name: SAST Scan

    permissions:
      security-events: write

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@7237412fdd36af517e2745077cedbf9d6900d711
      with:
        args: '. --sarif --output results.sarif || true'

  Build-Development:
    environment: development
    runs-on: ubuntu-latest
    needs: [Sast-Development]
    name: Node ${{ matrix.node-version }} Ubuntu Build

    strategy:
      matrix:
        node-version: [14.17.x, 16.x]

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - name: Build App
      run: |
        npm install
        npm run build
  
  Coverage-Tests:
    environment: development
    runs-on: ubuntu-latest
    name: Coverage Tests - Node ${{ matrix.node-version }}
    needs: [Build-Development]

    strategy:
      matrix:
        node-version: [14.17.x, 16.x]

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - name: Install Dependencies
      run: |
        npm install
  
    - name: Cypress Coverage
      run: npm run test:ci

    - name: Cypress e2e
      run: npm run test:cypress:ci

    - name: Coveralls push
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}